### ISSUE TITLE
display failed

### ISSUE THREAD

**Issue by YisongCai666** [xiaozhuchacha/VCLATactileGlove#1]
Hello，It‘s my honor to use your source to study,but I can not work well with your code .I can roslanch the display.launch,but it seems lack of some neccessiry files.Can you provide me a complete code? Looking forward to your reply ,thanks!

**Comment by xiaozhuchacha** [comment]
Can you be more specific? Do you have a complete replicate of the glove hardware?

**Comment by YisongCai666** [comment]
Thanks for your reply!Yes,but it seems that it lacks of the file "bottle64_open_palm_"  under the route "/home/xuxie/catkin_ws/src/tac_glove/bottle64/open_palm/" as well as lacks of the package "tf",so that I can not display in rviz.

**Comment by liuhx111** [comment]
See the comments in the updated launch file. Just let us know if you have further problems.

**Comment by YisongCai666** [comment]
I launch the launch file but it still can not work，then I only check the hand.urdf.xacro but it cannot show the model as well as the position of all joints show zero

**Comment by liuhx111** [comment]
The code is designed to show zero joint positions until a proper IMU data stream is fed. The package currently only works with the designated hardware presented in the paper. You may need to modify the package according to your setup.

**Comment by YisongCai666** [comment]
I want to know if the Raspberry should enter the root mode and 
rosrun imutracker before I  launch the display.launch. Can you provide me the steps to start your code and the necessary Installation Package，so that I can check where my environment setup need to modify.

**Comment by liuhx111** [comment]
All required codes are in the package. Below is several key steps worth attention:

(1) Make sure you configure your Raspberry Pi properly so that its I2C ports are enabled. 
(2) Configure your ROS environment in the Raspberry Pi and your network (ROS_MASTER_URL and ROS_IP). Pi doesn't support full ROS functions (no RVIZ etc.). We run the roscore in another PC. Pi is the slave that only streams data to the PC. 
(3) We usually launch the display.launch in the PC first.
(4) Run imutracker in the Raspberry Pi with root to publish IMU data.
